version: 2.1

jobs:
  create_network:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Network Stack
          command: |
            aws cloudformation create-stack \
              --stack-name $NETWORK_STACK_NAME \
              --template-body file://network.yml \
              --parameters file://network_param.conf \
              --capabilities CAPABILITY_IAM

  create_app_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create App Infra Stack
          command: |
            aws cloudformation create-stack \
              --stack-name ApplicationStack \
              --template-body file://app_infra.yml \
              --parameters file://app_param.conf \
              --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

workflows:
  deploy:
    jobs:
      - create_network
      - create_app_infra